//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class salgrade
    {
        public int grade { get; set; }
        public Nullable<decimal> losal { get; set; }
        public Nullable<decimal> hisal { get; set; }
    }
}
